CovidWeb.FL2/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CovidWeb.Models
{
    public class Country
    {
        public string Name { get; set; }
    }
}

CovidWeb.FL2/Models/DTO/CountryDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CovidWeb.Models.DTO
{
    public class CountryDto
    {
        public string Country { get; set; }
        //public string Slug { get; set; }
        //public string ISO2 { get; set; }
    }
}

CovidWeb.FL2/Models/DTO/Global.cs
namespace CovidWeb.Models.DTO
{
    public class Global
    {
        public int NewConfirmed { get; set; }
        public int TotalConfirmed { get; set; }
        public int TotalDeaths { get; set; }
    }
}

CovidWeb.FL2/Models/DTO/SummaryDTO.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace CovidWeb.Models.DTO
{
    public class SummaryDTO
    {
        public Global Global { get; set; }
        public List<SummaryDetailDto> Countries { get; set; }
    }
}

CovidWeb.FL2/Models/DTO/SummaryDetailDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CovidWeb.Models.DTO
{
    public class SummaryDetailDto
    {
        public string Country { get; set; }
        public int NewConfirmed { get; set; }
        public int TotalConfirmed { get; set; }
        public int NewDeaths { get; set; }
        public int TotalDeaths { get; set; }
        public int NewRecovered { get; set; }
        public int TotalRecovered { get; set; }
        public DateTime Date { get; set; }
    }
}

CovidWeb.FL2/Models/ViewModels/SummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using CovidWeb.Models.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CovidWeb.Models.ViewModels
{
    public class SummaryViewModel
    {
        [Display(Name = "Nya bekräftade fall")]
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString = "{0:N0} st")]
        public int NewConfirmed { get; set; }

        [Display(Name = "Totala antalet bekräftade fall")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:N0}")]
        public int TotalConfirmed { get; set; }
        public int TotalDeaths { get; set; }
        [DisplayFormat(DataFormatString = "{0:dddd dd MMMM}")]
        public DateTime Date { get; set; }

        private List<Country> countries;

        public string SelectedCountry { get; set; } = "Sweden";
        
        [Display(Name ="Välj land")]
        public IEnumerable<SelectListItem> Countries
        {
            get
            {
                if (countries != null)
                {
                    return countries.Select(x =>
                    new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Name
                    });
                }
                return null;
            }
        }

        public SummaryViewModel(IEnumerable<CountryDto> countries, SummaryDetailDto summaryDetail)
        {
            // ger alla värden till våra properties
            if (summaryDetail != null)
            {
                NewConfirmed = summaryDetail.NewConfirmed;
                TotalConfirmed = summaryDetail.TotalConfirmed;
                TotalDeaths = summaryDetail.TotalDeaths;
                Date = summaryDetail.Date;
            }
            

            // gör om countryDto till en lista av countries
           this.countries = countries
                .Select(c => new Country
                {
                    Name = c.Country
                })
                .OrderBy(x => x.Name)
                .ToList();
        }

        public SummaryViewModel()
        {

        }
    }
}

CovidWeb.FL2/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using CovidWeb.Data;
using CovidWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

namespace CovidWeb.Controllers
{
    public class AboutController : Controller
    {

        private ICovidRepository repository;

        public AboutController(ICovidRepository repository)
        {
            this.repository = repository;
        }
        // [Route("")]

        [Route("/about")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var watch = System.Diagnostics.Stopwatch.StartNew();
            var viewModel = await repository.GetSummaryViewModel();
            watch.Stop();
            var time = watch.ElapsedMilliseconds;
            return View(viewModel);
        }
        [HttpGet("About/Search")]
        public async Task<IActionResult> Search(SummaryViewModel model)
        {
            ModelState.Clear();
            var viewModel = await repository.GetSummaryViewModel(model.SelectedCountry);
            viewModel.SelectedCountry = model.SelectedCountry;
            return View("index", viewModel);
        }


    }
}

CovidWeb.FL2/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CovidWeb.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CovidWeb.FL2/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CovidWeb.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CovidWeb.FL2/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CovidWeb.Data;
using CovidWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CovidWeb.Controllers
{
    public class StartController : Controller
    {
        private ICovidRepository covidRepository;
        public StartController(ICovidRepository covidRepository)
        {
            this.covidRepository = covidRepository;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
           var model =  await covidRepository.GetCountries();
           return View(model);

            }
            catch (Exception)
            {

                return RedirectToAction("index", "error");
            }
        }


        public async Task<IActionResult> Summary()
        {
            //TODO: Fixa så att man kan skicka in både summary och country
            var summary = await covidRepository.GetSummary();
           // var model = new SummaryViewModel(summary);
            

            return View(summary);
        }


    }
}

CovidWeb.FL2/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CovidWeb.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        public MenuViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync(string activePage)
        {
            await Task.Delay(0);
            return View("Default");
        }
    }
}

CovidWeb.FL2/Views/About/Index.cshtml
@model CovidWeb.Models.ViewModels.SummaryViewModel
@section scripts {
    <script src="~/js/formHandler.js"></script>
}
<div class="fh5co-hero" style="background-image: url(//images/hero_4.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Status</h1>
                    <p>Covid</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h2>Teset</h2>
                <form asp-action="Search" asp-controller="About" method="get">
                    <p>@Html.DisplayNameFor(x => x.Countries)</p>

                    <p>@Html.DropDownListFor(x => Model.SelectedCountry, new SelectList(Model.Countries, "Value", "Text"), "Välj land", new { @onchange = "onChange(this.value)" })</p>
                    <br />
                    <p>@Html.DisplayNameFor(model => model.TotalConfirmed)</p>
                    <p><input asp-for="TotalConfirmed" type="text" /></p>
                    @*<p> @Html.TextBoxFor(x => x.TotalConfirmed)</p>*@
                    <p>@Html.DisplayNameFor(model => model.NewConfirmed)</p>
                    <p>@Html.DisplayFor(model => model.NewConfirmed)</p>

                    <p>@Html.DisplayNameFor(model => model.TotalConfirmed)</p>
                    <p>@Html.DisplayFor(model => model.TotalConfirmed)</p>

                    <p>@Html.DisplayNameFor(model => model.Date)</p>
                    <p>@Html.DisplayFor(model => model.Date)</p>
                    <button type="submit">OK</button>
                </form>
                </div>
                <div class="col-md-7">
                    <img src="/images/hero_1.jpg" alt="Free HTML5 by FreeHTML5.co" class="img-responsive">
                </div>
            </div>
    </div>
</div>

<div class="fh5co-parallax" style="background-image: url(//images/hero_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">The leadership</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 fh5co-staff">
                <img src="/images/person3.jpg" alt="Free HTML5 Bootstrap Template" class="img-responsive">
                <h3>Athan Smith</h3>
                <h4>Co-Founder, CEO</h4>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <ul class="fh5co-social">
                    <li><a href="#"><i class="icon-google"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>
            <div class="col-md-4 fh5co-staff">
                <img src="//images/person2.jpg" alt="Free HTML5 Bootstrap Template" class="img-responsive">
                <h3>Nathalie Kosley</h3>
                <h4>Co-Founder, CTO</h4>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <ul class="fh5co-social">
                    <li><a href="#"><i class="icon-google"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>
            <div class="col-md-4 fh5co-staff">
                <img src="///images/person4.jpg" alt="Free HTML5 Bootstrap Template" class="img-responsive">
                <h3>Yanna Kuzuki</h3>
                <h4>Co-Founder, Principal</h4>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <ul class="fh5co-social">
                    <li><a href="#"><i class="icon-google"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="fh5co-parallax" style="background-image: url(/images/hero_3.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Keep it simple</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fh5co-section">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <h2>Start A Project With Us Now!</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.</p>

            </div>
            <div class="col-md-6">
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <p><a href="#" class="btn btn-primary">Get started now!</a></p>
            </div>
        </div>

    </div>
</div>

CovidWeb.FL2/Views/Contact/Index.cshtml
<div class="fh5co-hero" style="background-image: url(/images/hero_3.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Contact us</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h2>Contact Info</h2>
                <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains.</p>

                <p>198 West 21th Street, Suite 721 <br> New York NY 10016</p>
                <p><a href="#">info@domain.com</a></p>
                <p><a href="#">+123 456 7890</a></p>
            </div>
            <div class="col-md-6 col-md-push-1">
                <form action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="" id="" cols="30" rows="10" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary btn-md">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="map"></div>

CovidWeb.FL2/Views/Services/Index.cshtml
<div class="fh5co-hero" style="background-image: url(/images/hero_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Our services</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h2>E Commerce</h2>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. </p>
                <ul class="fh5co-check">
                    <li>Web Design</li>
                    <li>User Experience</li>
                    <li>User Interface</li>
                    <li>Search Engine Optimization</li>
                </ul>
            </div>
            <div class="col-md-7">
                <img src="/images/hero_1.jpg" alt="Free HTML5 by FreeHTML5.co" class="img-responsive">
            </div>
        </div>
    </div>
</div>

<div class="fh5co-parallax" style="background-image: url(/images/hero_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Simple yet elegant</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-push-7">
                <h2>Web Design</h2>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <ul class="fh5co-check">
                    <li>Web Design</li>
                    <li>User Experience</li>
                    <li>User Interface</li>
                    <li>Search Engine Optimization</li>
                </ul>
            </div>
            <div class="col-md-7 col-md-pull-5">
                <img src="/images/hero_1.jpg" alt="Free HTML5 by FreeHTML5.co" class="img-responsive">
            </div>
        </div>
    </div>
</div>


<div class="fh5co-parallax" style="background-image: url(/images/hero_3.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                <div class="fh5co-intro fh5co-table-cell">
                    <h1 class="text-center">Keep it simple</h1>
                    <p>Made with love by the fine folks at <a href="http://freehtml5.co">FreeHTML5.co</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fh5co-section">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <h2>Start A Project With Us Now!</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.</p>

            </div>
            <div class="col-md-6">
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                <p><a href="#" class="btn btn-primary">Get started now!</a></p>
            </div>
        </div>

    </div>
</div>

CovidWeb.FL2/Views/Shared/Components/Menu/Default.cshtml
<ul>
    <li>@Html.ActionLink("Startsida","Index", "Start")</li>
    <li><a href="#">Products</a></li>
    <li><a href="#">Services</a></li>
    <li><a href="#">Blog</a></li>
    <li><a href="#">Contact</a></li>
</ul>

CovidWeb.FL2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="sv-se" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Simple &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />

    <!--
      //////////////////////////////////////////////////////

      FREE HTML5 TEMPLATE
      DESIGNED & DEVELOPED by FreeHTML5.co

      Website: 		http://freehtml5.co/
      Email: 			info@freehtml5.co
      Twitter: 		http://twitter.com/fh5co
      Facebook: 		https://www.facebook.com/fh5co

      //////////////////////////////////////////////////////
       -->
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/css/animate.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/css/icomoon.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="~/css/style.css">

    <!-- Modernizr JS -->
    <script src="~/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="~js/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <div id="fh5co-wrap">
        <header id="fh5co-header">
            <div class="container">
                <nav class="fh5co-main-nav">
                    <ul>
                        @*<li>@Html.ActionLink("Om oss", "Index", "about") </li>*@
                        <li class="fh5co-active"><a href="/start"><span>Home</span></a></li>
                        <li><a href="/services"><span>Services</span></a></li>
                        <li>@Html.ActionLink("Om oss", "Index", "about") </li>
                        @* <li class="fh5co-active"><a href="/about"><span>About</span></a></li>*@
                        <li><a href="/contact"><span>Contact</span></a></li>
                    </ul>
                </nav>
            </div>
        </header>

        @RenderBody();



    </div> <!-- END fh5co-wrap -->


    <footer id="fh5co-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3>About Us</h3>
                    <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains.</p>
                </div>
                <div class="col-md-3 col-md-push-1">
                    <h3>Quick Links</h3>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Products</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-md-push-1">
                    <h3>Follow Us</h3>
                    <ul class="fh5co-social">
                        <li><a href="#"><i class="icon-twitter"></i> <span>Twitter</span></a></li>
                        <li><a href="#"><i class="icon-facebook"></i> <span>Facebook</span></a></li>
                        <li><a href="#"><i class="icon-instagram"></i> <span>Instagram</span></a></li>
                        <li><a href="#"><i class="icon-google"></i> <span>Google Plus</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 fh5co-copyright text-center">
                    <p><small>&copy; 2016 Free HTML5 Simple. All Rights Reserved. </small> <small>Made with care by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo /images: <a href="http://unsplash.com" target="_blank">Unsplash</a></small></p>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required:false)
    <!-- jQuery -->
    <script src="~js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~js/jquery.waypoints.min.js"></script>
    <!-- Stellar -->
    <script src="~js/jquery.stellar.min.js"></script>
    <!-- MAIN JS -->
    <script src="~js/main.js"></script>

</body>
</html>